export const REALTIME_RECONNECT_BASE_DELAY_MS = 1_000;

export const REALTIME_RECONNECT_MAX_DELAY_MS = 30_000;

export const REALTIME_CONNECTION_TIMEOUT_MS = 10_000;

export const REALTIME_NORMAL_CLOSE_CODE = 1000;
